name: AstraOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build frontend image
        run: docker build -t astraops-frontend:ci .

  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend deps
        working-directory: backend
        run: npm install

      - name: Build backend image
        run: docker build -t astraops-backend:ci ./backend
